#####
name: CycleGan
bidirect: False #Unidirectional or bidirectional
regist: True    # With or without registration network
noise_level: 1  #  noise level
port: 6019   #  port parameters
save_root: '/home/PET-CT/hachi/Reg-GAN/Checkpoint/phase2/augment/coronal/' #Cyc + NC+R
log_root: './output/log/augment/coronal/'
image_save: './output/img/'
val_log_path: './output/log3.txt'

# lamda weight
Adv_lamda: 1
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10


epoch: 0        # starting epoch
n_epochs: 80       # How often do you want to display output images during training
batchSize: 1               # size of the batches
dataroot: '/home/PET-CT/hachi/pet_phase2/train/'     # root directory of the dataset
val_dataroot: '/home/PET-CT/hachi/pet_phase2/val/'
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 256                # size of the data crop
input_nc: 1         
output_nc: 1                  
cuda: True                
n_cpu: 1

